name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi

      - name: Build
        env:
          TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TURBO_TEAM: ${{ secrets.VERCEL_TEAM }}
        run: |
          if [ -e yarn.lock ]; then
          yarn build
          else
          npm run build
          fi

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: |
          if [ -e yarn.lock ]; then
          yarn deploy-storybook -- --ci --existing-output-dir=storybook-static
          else
          npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
          fi
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}